name: breakout
description: "Create widgets that break out of their padded area"
version: 1.0.0-dev.2
homepage: https://github.com/LowLevelSubmarine/breakout
repository: https://github.com/LowLevelSubmarine/breakout

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
